name: Send message

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Send message
      run: |
        curl -X POST 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=cb6c67a2-8e6e-46cd-95fb-12014d909d5b' \
        -H 'Content-Type: application/json' \
        -d '{
          "msgtype": "text",
          "text": {
            "content": "abc很好"
          }
        }'
